import 'package:flutter/material.dart';

List<Map<String, dynamic>> fieldList = [
  {
    'logoUrl': 'assets/skilImages/none.png',
    'title': '없음',
    'titleColor': Colors.white,
    'badgeColor': Colors.black,
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/typescript.png',
    'title': 'TYPESCRIPT',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF037BCB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/javascript.png',
    'title': 'JAVASCRIPT',
    'titleColor': Colors.black,
    'badgeColor': const Color(0xFFF5DF1D),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/tailwindcss.png',
    'title': 'TAILWINDCSS',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF3DB1AB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/html.png',
    'title': 'HTML5',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFFE35026),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/css.png',
    'title': 'CSS3',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF1472B6),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/react.png',
    'title': 'REACT',
    'titleColor': Colors.black,
    'badgeColor': const Color(0xFF61DAFB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/npm.png',
    'title': 'NPM',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFFCB3837),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/yarn.png',
    'title': 'YARN',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF2C8EBB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/prettier.png',
    'title': 'PRETTIER',
    'titleColor': Colors.black,
    'badgeColor': const Color(0xFFF8B83E),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/eslint.png',
    'title': 'ESLINT',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF4B3263),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/figma.png',
    'title': 'FIGMA',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFFF24D1D),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/cLanguage.png',
    'title': 'C',
    'titleColor': const Color(0xFF3949AB),
    'badgeColor': Colors.white,
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/c++Language.png',
    'title': 'C++',
    'titleColor': const Color(0xFF00599C),
    'badgeColor': Colors.white,
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/java.png',
    'title': 'JAVA',
    'titleColor': const Color(0xFFEA2D2E),
    'badgeColor': const Color(0xFFF8F0E3),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/ruby.png',
    'title': 'RUBY',
    'titleColor': const Color(0xFFEC1622),
    'badgeColor': Colors.black,
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/python.png',
    'title': 'PYTHON',
    'titleColor': const Color(0xFFFDDC51),
    'badgeColor': const Color(0xFF5F5F5F),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/php.png',
    'title': 'PHP',
    'titleColor': const Color(0xFF8993BE),
    'badgeColor': const Color(0xFF232531),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/dart.png',
    'title': 'DART',
    'titleColor': const Color(0xFF00D2B8),
    'badgeColor': const Color(0xFF0082C8),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/swift.png',
    'title': 'SWIFT',
    'titleColor': const Color(0xFFFD7534),
    'badgeColor': const Color(0xFFFFFFFF),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/kotlin.png',
    'title': 'KOTLIN',
    'titleColor': const Color(0xFFB025EA),
    'badgeColor': const Color(0xFF000000),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/fortran.png',
    'title': 'FORTRAN',
    'titleColor': const Color(0xFF734F96),
    'badgeColor': const Color(0xFF0095F9),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/matlab.png',
    'title': 'MATLAB',
    'titleColor': const Color(0xFFFA8042),
    'badgeColor': const Color(0xFF583647),
    'isSelected': false,
  },
];
