import 'package:flutter/material.dart';

List<Map<String, dynamic>> fieldList = [
  {
    'logoUrl': 'assets/skilImages/typescript.png',
    'title': 'TYPESCRIPT',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF037BCB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/javascript.png',
    'title': 'JAVASCRIPT',
    'titleColor': Colors.black,
    'badgeColor': const Color(0xFFF5DF1D),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/tailwindcss.png',
    'title': 'TAILWINDCSS',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF3DB1AB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/html.png',
    'title': 'HTML5',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFFE35026),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/css.png',
    'title': 'CSS3',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF1472B6),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/react.png',
    'title': 'REACT',
    'titleColor': Colors.black,
    'badgeColor': const Color(0xFF61DAFB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/npm.png',
    'title': 'NPM',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFFCB3837),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/docker.png',
    'title': 'DOCKER',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF0BB7ED),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/yarn.png',
    'title': 'YARN',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF2C8EBB),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/prettier.png',
    'title': 'PRETTIER',
    'titleColor': Colors.black,
    'badgeColor': const Color(0xFFF8B83E),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/eslint.png',
    'title': 'ESLINT',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF4B3263),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/figma.png',
    'title': 'FIGMA',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFFF24D1D),
    'isSelected': false,
  },
];
