import 'package:flutter/material.dart';

List<Map<String, dynamic>> toolsList = [
  {
    'logoUrl': 'assets/skilImages/none.png',
    'title': '없음',
    'titleColor': Colors.white,
    'badgeColor': Colors.black,
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/github.png',
    'title': 'GITHUB',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF111011),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/notion.png',
    'title': 'NOTION',
    'titleColor': Colors.white,
    'badgeColor': Colors.black,
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/slack.png',
    'title': 'SLACK',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF4A144C),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/zoom.png',
    'title': 'ZOOM',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF2D8CFF),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/discord.png',
    'title': 'DISCORD',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF5765F2),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/intellij.png',
    'title': 'INTELLIJ',
    'titleColor': const Color(0xFFCE3F7B),
    'badgeColor': const Color(0xFF000000),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/vscode.png',
    'title': 'VISUAL STUDIO CODE',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF0078D7),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/notepad++.png',
    'title': 'NOTEPAD++',
    'titleColor': const Color(0xFF000000),
    'badgeColor': const Color(0xFF81C572),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/androidStudio.png',
    'title': 'ANDROID STUDIO',
    'titleColor': const Color(0xFFFFFFFF),
    'badgeColor': const Color(0xFF4285F4),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/eclipse.png',
    'title': 'ECLIPSE',
    'titleColor': const Color(0xFFF7941E),
    'badgeColor': const Color(0xFF41327C),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/auth0.png',
    'title': 'AUTH0',
    'titleColor': const Color(0xFFEB5424),
    'badgeColor': const Color(0xFFFFFFFF),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/jupyter.png',
    'title': 'JUPYTER',
    'titleColor': const Color(0xFF767677),
    'badgeColor': const Color(0xFFE9F2FD),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/docker.png',
    'title': 'DOCKER',
    'titleColor': Colors.white,
    'badgeColor': const Color(0xFF0BB7ED),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/stackOverflow.png',
    'title': 'STACK OVERFLOW',
    'titleColor': const Color(0xFFFF810F),
    'badgeColor': const Color(0xFFFFFFFF),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/postman.png',
    'title': 'POSTMAN',
    'titleColor': const Color(0xFFF15A24),
    'badgeColor': const Color(0xFF999999),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/nginx.png',
    'title': 'NGINX',
    'titleColor': const Color(0xFF019639),
    'badgeColor': const Color(0xFFFFFFFF),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/redis.png',
    'title': 'REDIS',
    'titleColor': const Color(0xFFFFFFFF),
    'badgeColor': const Color(0xFF722725),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/postgresql.png',
    'title': 'POSTGRESQL',
    'titleColor': const Color(0xFFFFFFFF),
    'badgeColor': const Color(0xFF336791),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/rabbitmq.png',
    'title': 'RABBITMQ',
    'titleColor': const Color(0xFFFF6600),
    'badgeColor': const Color(0xFF808080),
    'isSelected': false,
  },
  {
    'logoUrl': 'assets/skilImages/firebase.png',
    'title': 'FIREBASE',
    'titleColor': const Color(0xFFDD2C00),
    'badgeColor': const Color(0xFFFF9100),
    'isSelected': false,
  },
];
